import { prisma } from "@/lib/prisma";
import { InvoiceStatus, PaymentMethod, Prisma } from "@prisma/client";

type TX = Prisma.TransactionClient;

async function nextPaymentNumber(companyId: number, tx: TX): Promise<string> {
  const result = await tx.$queryRaw<{ max: bigint | null }[]>`
    SELECT MAX(CAST(SUBSTRING(payment_number, 5) AS UNSIGNED)) as max
    FROM payments WHERE company_id = ${companyId} AND payment_number LIKE 'PAY-%'
  `;
  return `PAY-${String(Number(result[0]?.max ?? 0) + 1).padStart(6, "0")}`;
}

async function nextReceiptNumber(companyId: number, tx: TX): Promise<string> {
  const result = await tx.$queryRaw<{ max: bigint | null }[]>`
    SELECT MAX(CAST(SUBSTRING(receipt_number, 5) AS UNSIGNED)) as max
    FROM receipts WHERE company_id = ${companyId} AND receipt_number LIKE 'REC-%'
  `;
  return `REC-${String(Number(result[0]?.max ?? 0) + 1).padStart(6, "0")}`;
}

interface RecordPaymentInput {
  companyId: number;
  invoiceId: number;
  amount: number;
  paymentMethod: PaymentMethod;
  paymentDate: Date;
  reference?: string | null;
  notes?: string | null;
  recordedBy?: number | null;
  isAutoGenerated?: boolean;
}

export async function recordPayment(input: RecordPaymentInput) {
  const {
    companyId, invoiceId, amount, paymentMethod, paymentDate,
    reference, notes, recordedBy, isAutoGenerated = false,
  } = input;

  if (amount <= 0) throw new Error("Payment amount must be greater than zero.");

  return prisma.$transaction(async (tx) => {
    const invoice = await tx.invoice.findFirst({
      where: { id: invoiceId, companyId },
      include: { payments: { select: { amount: true } } },
    });
    if (!invoice) throw new Error("Invoice not found.");
    if (invoice.status === InvoiceStatus.CANCELLED) throw new Error("Cannot pay a cancelled invoice.");
    if (invoice.status === InvoiceStatus.PAID && !isAutoGenerated) throw new Error("Invoice is already fully paid.");

    const alreadyPaid = invoice.payments.reduce((s, p) => s + Number(p.amount), 0);
    const remaining = Number(invoice.total) - alreadyPaid;

    if (!isAutoGenerated && amount > remaining + 0.001) {
      throw new Error(`Amount exceeds remaining balance of ${remaining.toFixed(2)}.`);
    }

    // Both number generators use tx — safe inside the transaction
    const paymentNumber = await nextPaymentNumber(companyId, tx);
    const receiptNumber = await nextReceiptNumber(companyId, tx);

    const payment = await tx.payment.create({
      data: {
        paymentNumber,
        companyId,
        invoiceId,
        clientId: invoice.clientId,
        amount,
        currency: invoice.currency,
        paymentMethod,
        reference: reference || null,
        paymentDate,
        notes: notes || null,
        recordedBy: recordedBy || null,
        isAutoGenerated,
      },
    });

    const totalPaidNow = alreadyPaid + amount;
    const newStatus = totalPaidNow >= Number(invoice.total) - 0.001
      ? InvoiceStatus.PAID
      : InvoiceStatus.PARTIAL;
    const balanceDue = Math.max(Number(invoice.total) - totalPaidNow, 0);

    await tx.invoice.update({
      where: { id: invoiceId },
      data: { status: newStatus },
    });

    const receipt = await tx.receipt.create({
      data: {
        receiptNumber,
        companyId,
        paymentId: payment.id,
        invoiceId,
        clientId: invoice.clientId,
        amount,
        currency: invoice.currency,
        balanceDue,
        issuedBy: recordedBy || null,
      },
    });

    return { payment, receipt, invoiceStatus: newStatus };
  });
}

export async function autoPayOnStatusChange(
  invoiceId: number,
  companyId: number,
  recordedBy?: number,
) {
  const invoice = await prisma.invoice.findFirst({
    where: { id: invoiceId, companyId },
    include: { payments: { select: { amount: true } } },
  });
  if (!invoice) return;

  const alreadyPaid = invoice.payments.reduce((s, p) => s + Number(p.amount), 0);
  const remaining = Number(invoice.total) - alreadyPaid;
  if (remaining <= 0.001) return;

  await recordPayment({
    companyId,
    invoiceId,
    amount: remaining,
    paymentMethod: PaymentMethod.BANK,
    paymentDate: new Date(),
    notes: "Auto-generated when invoice was marked as paid.",
    recordedBy: recordedBy || null,
    isAutoGenerated: true,
  });
}
